### ISSUE TITLE
More special characters

### ISSUE THREAD

**Issue by JoelMon** [huss-a/rust-passgen#1]
https://github.com/huss-a/rust-passgen/blob/846650093d35b5facfabd53fe3d33a7f71d02a4a/src/lib.rs#L3

Hello,

Just wanted to mention that there are a few more special characters missing from your  `static SPECIAL`. For example, `.`, `,`, ` and `~`.  You could add all of them then have a user option to list all the specials they *do not* want.

Maybe a `--exclude, -e` option that accept a space separated list of special characters not to be used.

**Comment by huss-a** [comment]
Got it! Thank you!
