### ISSUE TITLE
Incorporate Clap into the project

### ISSUE THREAD

**Issue by JoelMon** [huss-a/rust-passgen#2]
[Clap](https://clap.rs/) is a wonderful crate for command line argument parsing. It's super easy to set up as well.

The author of the crate also has a [tutorial on Youtube](https://www.youtube.com/playlist?list=PLza5oFLQGTl2Z5T8g1pRkIynR3E0_pc7U) that goes through using Clap. The tutorial helped me in my own project.

**Comment by huss-a** [comment]
Thanks for the suggestion! I'll check it out
